# Site settings
author: Emily Lillie
title: Emily's Programming Blog
header-img: img/home-bg.png
email: emilylillie3@gmail.com
copyright_name: Emily Lillie
description: > # this means to ignore newlines until "baseurl:"
  My trials and tribulations as I pivot careers
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  emilyLillie

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
